### ISSUE TITLE
General comments & Link for `Summarized_ExcelFile_by_Hyosun` not working?

### ISSUE THREAD

**Issue by rubendouglas-ne** [bbeyes81/GANs_Literature#1]
Hi @bbeyes81 

sorry its taken me a while to give feedback o this, really great work putting the review together :)

I wonder though if its necessary to have a separate repo for this. You can just add the `README.md` file to our Ai_for_peatlands Repo (maybe in a folder called "GANs" or similar).

I cant seem to open the `Summarized_ExcelFile_by_Hyosun` link- can you send it to me or put in on our shared onedrive folder?

look forward to our meeting on monday,

many thanks,
Ruben

**Comment by bbeyes81** [comment]
sorted out :)
